#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("android.kalkulator.Resource", IsApplication=true)]

namespace android.kalkulator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int theme_custom_background = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int theme_material_background = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000a
			public const int button0 = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int button00 = 2131099653;
			
			// aapt resource value: 0x7f060002
			public const int button1 = 2131099650;
			
			// aapt resource value: 0x7f060006
			public const int button18 = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int button2 = 2131099655;
			
			// aapt resource value: 0x7f06000c
			public const int button3 = 2131099660;
			
			// aapt resource value: 0x7f060003
			public const int button4 = 2131099651;
			
			// aapt resource value: 0x7f060008
			public const int button5 = 2131099656;
			
			// aapt resource value: 0x7f06000d
			public const int button6 = 2131099661;
			
			// aapt resource value: 0x7f060004
			public const int button7 = 2131099652;
			
			// aapt resource value: 0x7f060009
			public const int button8 = 2131099657;
			
			// aapt resource value: 0x7f06000e
			public const int button9 = 2131099662;
			
			// aapt resource value: 0x7f060010
			public const int buttonBagi = 2131099664;
			
			// aapt resource value: 0x7f060001
			public const int buttonC = 2131099649;
			
			// aapt resource value: 0x7f06000b
			public const int buttonDel = 2131099659;
			
			// aapt resource value: 0x7f060011
			public const int buttonKali = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int buttonMin = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int buttonPlus = 2131099667;
			
			// aapt resource value: 0x7f060014
			public const int buttonSamadengan = 2131099668;
			
			// aapt resource value: 0x7f06000f
			public const int buttonTitik = 2131099663;
			
			// aapt resource value: 0x7f060000
			public const int textView = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f020000
			public const int Main = 2130837504;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f030000
			public const int app_name = 2130903040;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Theme_Custom = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
